owner: jun2moon
repo: krima-status 

sites:
  - name: KRIMA Website
    url: https://military.co.kr
  - name: KRIMA Health Check
    url: https://military.co.kr/up/
    expectedStatusCode: 200

status-website:
  name: KRIMA Status

notifications:
  - type: email
    address: navhyun2017@naver.com
